name: GitHub Contribution Snake

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user: hamza64rtx  # هنا حط الإسم ديالك
          svg_out_path: "github-contribution-grid-snake.svg"

      - name: Upload Snake
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: github-contribution-grid-snake.svg
